# Base image
FROM node:20.15.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./fn/package.json ./fn/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY ./fn .

# Expose the port for the development server
EXPOSE 8081

# Start the React Native development server
CMD ["npm", "start"]
