# Generated by Django 5.1.1 on 2024-12-27 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscle_part', models.CharField(max_length=30)),
                ('sub_part', models.CharField(default='', max_length=30)),
                ('calorie_male', models.IntegerField(default=0)),
                ('calorie_female', models.IntegerField(default=0)),
                ('setnum', models.IntegerField(default=5)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBodyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAddPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('day', models.IntegerField()),
                ('muscle_part', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'day'), name='unique_type_day_add_exercise_micro')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('day', models.IntegerField()),
                ('muscle_part', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'day'), name='unique_type_day_main_exercise_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('right_arm_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('left_arm_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('body_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('right_leg_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('left_leg_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_id_date_muscle_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_id_date_weight_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultAbsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_abs_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultAnteriorDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_anteriordeltoid_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultBackExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_back_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultBackThighExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_backthigh_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultBicepsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_biceps_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultFrontThighExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_frontthigh_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultLateralDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_lateraldeltoid_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultLowerChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_lowerchest_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultMiddleChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_middlechest_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultPosteriorDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_posteriordeltoid_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultTricepsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_triceps_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultUpperChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_upperchest_micro')],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=60)),
                ('exercise_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date', 'exercise_id'), name='unique_user_id_date_exercise_id_exercise_done_micro')],
            },
        ),
    ]
