# Generated by Django 5.1.1 on 2024-10-30 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_allergy_exercise_food_ingredient_userbodymetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbodymetrics',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
