# Generated by Django 5.1.1 on 2024-10-31 01:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userbodymetrics_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBodyInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('right_arm_muscle_mass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('left_arm_muscle_mass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('body_muscle_mass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('right_leg_muscle_mass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('left_leg_muscle_mass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight_goal', models.IntegerField()),
                ('muscle_goal', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFridgeImage',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('base64image', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='musclepart',
            new_name='muscle_part',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='muscle_goal',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='weight_goal',
        ),
        migrations.AddField(
            model_name='food',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='UserBodyMetrics',
        ),
    ]
