# Generated by Django 5.1.1 on 2024-10-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userallergy',
            name='allergy_id',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.RemoveField(
            model_name='ingredientinfood',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='foodkeyword',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='ingredientinfood',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='userallergy',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodKeyword',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientInFood',
        ),
        migrations.DeleteModel(
            name='UserAllergy',
        ),
        migrations.DeleteModel(
            name='UserExercise',
        ),
    ]
