# Generated by Django 5.1.1 on 2024-11-13 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userallergy_allergy_id_delete_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbodyinfo',
            name='period_goal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='body_muscle_mass',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='left_arm_muscle_mass',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='left_leg_muscle_mass',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='right_arm_muscle_mass',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='right_leg_muscle_mass',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
