# Generated by Django 5.1.1 on 2024-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_userbodyinfo_body_muscle_mass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='muscle_goal',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='period_goal',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='weight_goal',
        ),
        migrations.AddField(
            model_name='user',
            name='exercise_plan_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbodyinfo',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
