# Generated by Django 5.1.1 on 2024-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_chest_recent_user_exercise_add_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exercise_plan_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='exercise_add_plan_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='exercise_main_plan_idx',
            field=models.IntegerField(default=0),
        ),
    ]
