# Generated by Django 5.1.1 on 2024-11-23 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_user_exercise_plan_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='body_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='left_arm_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='left_leg_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='right_arm_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='right_leg_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='userbodyinfo',
            name='weight',
        ),
        migrations.AddField(
            model_name='user',
            name='calorie_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbodyinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('right_arm_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('left_arm_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('body_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('right_leg_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('left_leg_muscle_mass', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_id_date_muscle')],
            },
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_id_date_weight')],
            },
        ),
    ]
