# Generated by Django 5.1.1 on 2024-11-23 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fivedaycalories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiveDayCalories',
            new_name='FiveDayCalorie',
        ),
    ]
