# Generated by Django 5.1.1 on 2024-11-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_fivedaycalories_fivedaycalorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fivedaycalorie',
            old_name='calories',
            new_name='calorie',
        ),
    ]
