# Generated by Django 5.1.1 on 2024-12-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_calories_fivedaycalorie_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.allergy')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food_id', 'allergy_id'), name='unique_food_id_allergy_id')],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food_id', 'category'), name='unique_food_id_category')],
            },
        ),
        migrations.CreateModel(
            name='FoodCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=30)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food_id', 'characteristic'), name='unique_food_id_characteristic')],
            },
        ),
    ]
