# Generated by Django 5.1.1 on 2024-12-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_cuisine_food_description_alter_food_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
