# Generated by Django 5.1.1 on 2024-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedfood',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
    ]
