# Generated by Django 5.1.1 on 2024-11-13 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='exercise_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='userexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'date_time'), name='unique_user_id_date_time_exercise'),
        ),
    ]
