# Generated by Django 5.1.1 on 2024-11-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_userexercise_duration_userexercise_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='exercise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
