# Generated by Django 5.1.1 on 2024-11-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_rename_userexercise_userexercisedone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAddPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('day', models.IntegerField()),
                ('muscle_part', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'day'), name='unique_type_day_add_exercise')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseMainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('day', models.IntegerField()),
                ('muscle_part', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'day'), name='unique_type_day_main_exercise')],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_part', models.CharField(max_length=30)),
                ('exercise_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserExercisePlan',
        ),
        migrations.AddConstraint(
            model_name='userdefaultexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'muscle_part'), name='unique_user_id_muscle_part_exercise'),
        ),
    ]
