# Generated by Django 5.1.1 on 2024-12-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exerciseaddplan_exercisemainplan_userdefaultexercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calorie',
        ),
        migrations.AddField(
            model_name='exercise',
            name='calorie_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='calorie_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sub_part',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='setnum',
            field=models.IntegerField(default=5),
        ),
    ]
