# Generated by Django 5.1.1 on 2024-12-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_remove_exercise_calorie_exercise_calorie_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefaultexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
