# Generated by Django 5.1.1 on 2024-12-03 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_userdefaultexercise_exercise_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaultAbsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultAnteriorDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultBackExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultBackThighExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultBicepsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultFrontThighExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultLateralDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultLowerChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultMiddleChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultPosteriorDeltoidExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultTricepsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefaultUpperChestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdefaultexercise',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='userdefaultexercise',
            name='user_id',
        ),
        migrations.RemoveConstraint(
            model_name='userexercisedone',
            name='unique_user_id_date_time_exercise',
        ),
        migrations.RemoveField(
            model_name='userexercisedone',
            name='date_time',
        ),
        migrations.AddField(
            model_name='userexercisedone',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='userexercisedone',
            constraint=models.UniqueConstraint(fields=('user_id', 'date', 'exercise_id'), name='unique_user_id_date_exercise_id_exercise_done'),
        ),
        migrations.AddField(
            model_name='userdefaultabsexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultabsexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultanteriordeltoidexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultanteriordeltoidexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultbackexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultbackexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultbackthighexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultbackthighexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultbicepsexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultbicepsexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultfrontthighexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultfrontthighexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultlateraldeltoidexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultlateraldeltoidexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultlowerchestexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultlowerchestexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultmiddlechestexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultmiddlechestexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultposteriordeltoidexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultposteriordeltoidexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaulttricepsexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaulttricepsexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdefaultupperchestexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='userdefaultupperchestexercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserDefaultExercise',
        ),
        migrations.AddConstraint(
            model_name='userdefaultabsexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_abs'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultanteriordeltoidexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_anteriordeltoid'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultbackexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_back'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultbackthighexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_backthigh'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultbicepsexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_biceps'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultfrontthighexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_frontthigh'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultlateraldeltoidexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_lateraldeltoid'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultlowerchestexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_lowerchest'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultmiddlechestexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_middlechest'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultposteriordeltoidexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_posteriordeltoid'),
        ),
        migrations.AddConstraint(
            model_name='userdefaulttricepsexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_triceps'),
        ),
        migrations.AddConstraint(
            model_name='userdefaultupperchestexercise',
            constraint=models.UniqueConstraint(fields=('user_id', 'exercise_id'), name='unique_user_id_exercise_id_upperchest'),
        ),
    ]
