# Generated by Django 5.1.1 on 2024-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calorie_bound_num',
            field=models.IntegerField(default=0),
        ),
    ]
